### ISSUE TITLE
[Bug] Can't install many plugins

### ISSUE THREAD

**Issue by cmalvi** [SteamDeckHomebrew/decky-loader#206]
The install seems finish successfully but the plugin doesn't appear in installed plugins

Examples: 
- CSS Loader (any version above 1.0.0)
- Audio Loader (any version)
- DeckFAQs (any version above 1.2.1)

**Comment by PartyWumpus** [comment]
Are you running on the most recent version? If you are, try rebooting to see if that helps.

**Comment by cmalvi** [comment]
> Are you running on the most recent version? If you are, try rebooting to see if that helps.

yes, lastest version and already tried rebooting

**Comment by TrainDoctor** [comment]
@cmalvi 
Please reboot your deck then in this order:
a. Please go to the settings menu and uninstall then reinstall the plugins with their latest versions.
b. Use ``journalctl -b0 -u plugin_loader.service > loader-py.log`` to get the logs from your most recent boot til you reinstalled the plugins.
c. Provide a version number and a image/screenshot of your QAM interface w/ the shop icon and settings icon in view.

**Comment by cmalvi** [comment]
i did the test with the plugin i've mentioned in the first post

**Comment by TrainDoctor** [comment]
According to testers, this issue should be solved on pre-release v2.2.3-pre1. Please install this version via the pre-release install script if you can't get the update notification. @cmalvi

**Comment by cmalvi** [comment]
> According to testers, this issue should be solved on pre-release v2.2.3-pre1. Please install this version via the pre-release install script if you can't get the update notification. @cmalvi 

According to my test, the issue is still present in v2.2.3-pre1

**Comment by cmalvi** [comment]
Still present in lastest preview update

**Comment by jayp76** [comment]
[loader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9838448/loader.log)

**Comment by Sashka69** [comment]
Same strange problem here. 
Both versions - stable and pre - show only plugins WITH ROOT PERMISSIONS. so system toolbox and powertools show up in the plugin list but vibrantdeck and fantastic and the css loader wont.

So why does decky detect plugins with needed root permissions?
Can somebody rebuild vibrantdeck, fantastic and css WITH needed root permissions? Maybe thats the trick for a dirty workaround...

**Comment by TrainDoctor** [comment]
@Sashka69 please upload the resulting file from running the below command which will be found in ``~/homebrew``:
``journalctl -b0 -u plugin_loader.service > loader-py.log``
If you join our discord I can show you how to grab another set of logs which would make it significantly easier to help you.
👍🏻

**Comment by Sashka69** [comment]
[loader-py.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9874625/loader-py.log)

i hope this helps

**Comment by DarylMcTech** [comment]
[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9914621/backend.log)

So, I cannot install any plugins other than ProtonDB Badges and System Toolbox. I'm running the latest SteamOS pre-release as well as the latest Decky pre-release, re-installed completely (including new directory files) just a few minutes ago. Attached is the only just created log file. Hope there will be a fix for this...

**Comment by hironkmn** [comment]
[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9971959/backend.log)
Same problem as @DarylMcTech. My set-up has nothing in particular. I just have EmuDeck and SyncThingy installed.

**Comment by PartyWumpus** [comment]
>I just have EmuDeck and *SyncThingy* installed.

If you check the common issues section in the readme:
`Syncthing may use port 8080 on Steam Deck, which Decky Loader needs to function. If you are using Syncthing as a service, please change its port to something else.`
this is probably your issue.
@hironkmn

**Comment by cmalvi** [comment]
Mine still present

**Comment by hironkmn** [comment]
@PartyWumpus I have verified, Syncthing use an another port

**Comment by ArnauS197** [comment]
Hi, same issue here, both stable and pre versions tried, no success. CSSLoader, Vibrantdeck, fantastic don't install. 

Latest stable version in both steam and decky

**Comment by helliongame** [comment]
my issue is the same as @Sashka69 , as i explained on #279 . i didn't know that only plugins with root permission are showed...but CSS and vibrantdeck are not  , and not showed on Decky overlay

**Comment by jurassicplayer** [comment]
@helliongame Can you post the result of `tree -ug ~/homebrew/plugins > plugin-permissions.log`

**Comment by helliongame** [comment]
> @helliongame Can you post the result of `tree -ug ~/homebrew/plugins > plugin-permissions.log`

i will post the results this afternoon on CET time.

Greetings

**Comment by helliongame** [comment]
here 

@jurassicplayer 
[plugin-permissions.log](https://github.com/SteamDeckHomebrew/decky-loader/files/10219070/plugin-permissions.log)

**Comment by xinelogit** [comment]
Same issue here, some plugins work (Powertools), some others don't (VibrantDeck, Fantastic, etc).
Owner is the same for all plugins folders, default user "deck", so I don't think the issue is related to permissions.

Let me know if you need further log details.

**Comment by TrainDoctor** [comment]
> Let me know if you need further log details.

@xinelogit Yes, please go ahead and attach your logs.

**Comment by ArnauS197** [comment]
I don't think either, I tried a chown+chmod 777 but nothing, same issue with vibrantdeck, cssloader...

**Comment by Kawhifmvp** [comment]
I have the same problem, after updating my system to 3.3.3 stable version, some plugins don't work and can't be displayed properly, such as vibrandeck. but powertools works.

**Comment by Kawhifmvp** [comment]
I have the same problem, after updating my system to 3.3.3 stable version, some plugins don't work and can't be displayed properly, such as vibrandeck. but powertools works.

**Comment by xinelogit** [comment]
> > Let me know if you need further log details.
> 
> @xinelogit Yes, please go ahead and attach your logs.
[loader-py.log](https://github.com/SteamDeckHomebrew/decky-loader/files/10232407/loader-py.log)
[plugin-permissions.log](https://github.com/SteamDeckHomebrew/decky-loader/files/10232420/plugin-permissions.log)

Attached.

**Comment by borja1990** [comment]
> I have the same problem, after updating my system to 3.3.3 stable version, some plugins don't work and can't be displayed properly, such as vibrandeck. but powertools works.

Same here, with same bug.

**Comment by Dellyare** [comment]
> I have the same problem, after updating my system to 3.3.3 stable version, some plugins don't work and can't be displayed properly, such as vibrandeck. but powertools works.

Same.

**Comment by treash83** [comment]
Good day, today I also faced this problem. Checked on all versions of system.
All day I tried different versions of decky and system. As an experiment, I installed all plugins from the standard store.
[loader-py.log](https://github.com/SteamDeckHomebrew/decky-loader/files/10238042/loader-py.log)
[plugin-permissions.log](https://github.com/SteamDeckHomebrew/decky-loader/files/10238045/plugin-permissions.log)

**Comment by TrainDoctor** [comment]
@treash83 these are both going to be very helpful for debugging the issue, thanks for doing this. I've tried similar experiments on my own hardware but I was unable to replicate the issue.

**Comment by treash83** [comment]
@TrainDoctor, I don't have experience with linux. Can these operations lead to problems with decky?

kwrite /etc/pacman.conf
add #:
#SigLevel    = Required DatabaseOptional
add new:
SigLevel = TrustAll

sudo pacman-key --init

sudo pacman -S glibc

kwrite /etc/locale.gen
delete #:
#ru_RU.UTF-8 UTF-8

sudo locale-gen

sudo localectl set-locale ru_RU.UTF-8

sudo steamos-readonly enable

**Comment by TrainDoctor** [comment]
@treash83 the update to glibc could be a factor, although I wouldn't be sure how. Thanks for your honesty. We generally don't support modified RO filesystems so do keep that in mind.

**Comment by treash83** [comment]
I change locale 
sudo localectl set-locale en_US.UTF-8
and problem is gone.

**Comment by Kawhifmvp** [comment]
@treash83 This does not work for me, how exactly does this work?I tried to use various methods to solve the day, but still no results

**Comment by Kawhifmvp** [comment]
@treash83 Please tell me exactly how you do it?

**Comment by Kawhifmvp** [comment]
@treash83 my problem is solved too. I switched the version of decky from prerelease to stable and sudo localectl set-locale en_US.UTF-8    All problems solved, thank you very much

**Comment by jayp76** [comment]
@TrainDoctor I also switched locale from de_DE.UTF-8 to en_US.UTF and the problem is fixed. Can Decky loader be modified so that we can use other UTF-8 locales?

**Comment by hironkmn** [comment]
@TrainDoctor Same for me. I switched to en_US.UTF-8 and all is working now. Thanks for the tip @treash83 !

**Comment by WerWolv** [comment]
I potentially fixed this issue in commit a3f0163503dcbd449f0fa0efd3fd9e9e8201b9cd.

If you can, please download the new build here https://github.com/SteamDeckHomebrew/decky-loader/actions/runs/3712933178 and place the file inside the zip in `\home\deck\homebrew\services`

**Comment by YukiCoco** [comment]
> I potentially fixed this issue in commit [a3f0163](https://github.com/SteamDeckHomebrew/decky-loader/commit/a3f0163503dcbd449f0fa0efd3fd9e9e8201b9cd).
> 
> If you can, please download the new build here https://github.com/SteamDeckHomebrew/decky-loader/actions/runs/3712933178 and place the file inside the zip in `\home\deck\homebrew\services`

Yes it fixed the locale issues, I did the same thing two hours ago 🤣.
https://github.com/YukiCoco/decky-loader/commit/3ee44a09dd8baa96d5948d4b316a965c1ff90c7b

**Comment by TrainDoctor** [comment]
This issue should now be fixed for all users which they can try on the pre-release branch, with a stable branch release hopefully soon to follow.

**Comment by cmalvi** [comment]
I can confirm is fixed without changing locale settings, thanks this bug bother me for months
