### ISSUE TITLE
Switching from desktop to gaming mode does not always load decky

### ISSUE THREAD

**Issue by LolRiTTeR** [SteamDeckHomebrew/decky-loader#245]
Hello!

I've noticed that when switching from desktop back to gaming mode decky does not always load, the icon will not show up. This appears to be random, because sometimes decky loads up just fine.

A possible workaround for this is to give the plugin_loader service a restart before going back to gaming mode.
I've been testing this for a couple days now and so far decky has loaded up every time when switching back and forth.

SteamOS stable update channel
Decky version v2.3.1-pre3
Installed plugins: PowerTools, SteamlessTimes

**Comment by AAGaming00** [comment]
I believe this is caused by https://github.com/SteamDeckHomebrew/decky-loader/blob/db7bb236d87fab6163612a61ae62a4e5389d92cd/backend/main.py#L142 not accounting for if the socket disconnects without sending a CDP detach message.

A solution for this would be to simply trigger that on socket disconnect instead of on CDP detach event.

**Comment by LolRiTTeR** [comment]
Wanted to give a quick update since decky has been updated too. Problem still persists.
(Workaround still works too)
decky v2.4.0-pre1

I also wanted to attach a loader.log, so here you go.
The last entries from 16:56 were ones where it didnt load after switching.
[loader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9982692/loader.log)

**Comment by TrainDoctor** [comment]
https://github.com/SteamDeckHomebrew/decky-loader/blob/b44896524f44fd862f9a385147cd755104a09cdc/backend/main.py#L143

The logic below this if statement needs to be triggered when connection is lost with the CEF Debug Protocol (CDP).

**Comment by TrainDoctor** [comment]
This should now be resolved, most recent pre-release incorporates the fix. If this works for reporting users then the issue will be closed as resolved.

**Comment by blacklabel2020** [comment]
Still having this issue, I'm on Stable for the OS and v2.4.1-pre1 for Decky but going from desktop mode then back to game mode the dexky icon disappears and I would need to reboot my steam deck

**Comment by TrainDoctor** [comment]
> Still having this issue, I'm on Stable for the OS and v2.4.1-pre1 for Decky but going from desktop mode then back to game mode the dexky icon disappears and I would need to reboot my steam deck

Thanks for your comment. We realized with followup testing that the issue wasn't fully addressed and on some systems would still occur. We're working to put another patch out when we can.

**Comment by TrainDoctor** [comment]
@blacklabel2020 if you are willing, we need a user who can reproduce the issue for our testing. If you can join our discord and post in the ``testing`` channel then we'd greatly appreciate it.

**Comment by TrainDoctor** [comment]
Testers indicate this has been fixed on the #254 PR branch.

**Comment by ahydronous** [comment]
@TrainDoctor I just installed Decky on 3.3.2 stable. Icon doesn’t appear in QAS, not even after a full reboot.

Doesn’t matter if Decky is Stable or Prerelease.

**Comment by XTREEMMAK** [comment]
Dealing with this now. Just did fresh install of either release on 3.3.2 and not getting the icon.

**Comment by ahydronous** [comment]
@XTREEMMAK weirdly enough installing PowerTools via the EmuDeck GUI installer made the Decky icon appear properly and permanently, you could try that
