### ISSUE TITLE
[BUG] Decky panel in QAM displayed over the new soundtrack panel in latest Steam beta

### ISSUE THREAD

**Issue by Cutotopo** [SteamDeckHomebrew/decky-loader#435]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

On the latest Steam beta, when the icons in the QAM for either the Decky or the new Soundtracks panel are selected, both panels are displayed simultaneously.

Steps to reproduce:
 1. Update to the latest Steam version on the beta branch
 2. From the Steam Deck home, press the QAM button
 3. Select either the Soundtracks or the Decky icon at the left of the panel

### Expected Behaviour

The contents of the "Decky" and "Soundtrack" panels are not displayed simultaneously.

### SteamOS version

SteamOS 3.4.6 Beta

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11359447/deckylog.txt)

**Comment by PartyWumpus** [comment]
This should already be fixed in the latest prerelease

**Comment by henrebotha** [comment]
I have the latest Decky prerelease and am still seeing this issue.

**Comment by henrebotha** [comment]
Ah, running the Decky installer again from the desktop fixed it. Maybe the Decky self-update mechanism isn't working correctly?

**Comment by Cutotopo** [comment]
Thanks! Running the installer again downloaded the latest version, with this bug fixed. Sorry for not checking if I was up to date, I simply clicked the "check for updates" in the Decky settings and did not check on Github.

**Comment by henrebotha** [comment]
I mean it certainly is a bug if the in-app checker says "nope we're good, up to date boss, nothing to report" when in fact it is not up to date. Users should be able to trust what the app says.

**Comment by matthewclaussen** [comment]
I had this same issue. Checking from inside Decky with the prerelease channel picked showed that 2.7.0 was the latest update and all was good. Like others here, I had to run the install script to get the 2.7.3-pre2 update.

**Comment by PartyWumpus** [comment]
This should now be fixed in release v2.7.4, although the prerelease updater not working is a bug I _have_ managed to reproduce once so will open a new issue for that if I can consistently get it to happen. Thanks for the reports.
