### ISSUE TITLE
[BUG] Decky crashes on 3.7.17 (stable)

### ISSUE THREAD

**Issue by ROODAY** [SteamDeckHomebrew/decky-loader#870]
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Decky doesn't load/doesn't appear in sidebar.

1. Updated to latest stable SteamOS
2. Updated to latest stable Decky
3. Restarted Steam Deck

At first some of the UI was glitching, but after some restarts it went away. I think because it just stops trying to load Decky. I'm guessing some plugin that changes CSS is conflicting? I don't want to delete all my plugins though, is there any way to disable them and add them back one by one and keep their configs?

I also did a hard restart and got to some boot loaderish page that said some error about Shared SteamUI_1033.. and then the screen changed before I could write down any more.

### Expected Behaviour

Decky should work/load/appear in the sidebar.

### SteamOS version

SteamOS 3.7.17 Stable

### Selected Update Channel

Stable

### Decky Loader Version

v3.2.1

### Plugin Info

[plugin-info.txt](https://github.com/user-attachments/files/24332587/plugin-info.txt)

### Have you modified the read-only filesystem at any point?

Emudeck? I'm not sure if this applies

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/24332588/deckylog.txt)

### Frontend Logs

[cef_log.previous.txt](https://github.com/user-attachments/files/24332622/cef_log.previous.txt)
[cef_log.txt](https://github.com/user-attachments/files/24332621/cef_log.txt)

**Comment by ROODAY** [comment]
Sidenote, the `plugin-info.sh` script did not work for me on my deck as is, I had to modify it slightly: https://github.com/SteamDeckHomebrew/decky-loader/pull/869

**Comment by JTDST** [comment]
I’ve been having this issue for a little while too. Deck keeps restarting and extracting package, constant loop. I’ve tried multiple installs and uninstalls to no avail. I really don’t want to completely reset my steam deck to get Decky working again but I feel even when I uninstall it something must be getting left installed. 

When the Deck does launch in game mode I keep getting the following error screens and Decky simply missing from the QAM.

![Image](https://github.com/user-attachments/assets/1588c71f-36ec-4df0-be53-98c3df444310)
![Image](https://github.com/user-attachments/assets/44809004-4077-4fbd-b1f0-237e09cb2d4b)
![Image](https://github.com/user-attachments/assets/2b0fbb4d-6bde-4329-83b7-1c4676357180)

**Comment by lowdown1983** [comment]
I was having the same issue as all of you with the same error and screen (i believe it was identical).  I was able to bypass it by clicking the option to disable decky loader until next boot.  Then i ran the installer again and uninstalled.  The problem persisted so I ran it again and chose the option to delete plugin data (or something like that) along with the uninstall.  That fixed the problem.  Well, when i booted up my steam deck today i seen there was an OS update so I updated, and checked if there were any fixes for decky loader, and for some reason decided to reinstall decky.  I did and it worked and booted no problem.  I installed Wine cellar, volume mixer, storage cleaner, steamgridDB, powertoola, PIP, FreeLoader, LetmeReshade, Animation Changer, Autoflatpks, DeckMTP, Framegen, Undervolt, Fantastic, and CHeatdeck.   No problems for an hour or so.  Then the screen from above popped up again, except this time, below the "Stable" and  "Check for Updates" buttons,  there was an option to uninstall cheatdeck.  i clicked it and steam rebooted.  that was a few hours ago and havent had any problems since.

**Comment by ynhhoJ** [comment]
@ROODAY, I checked your logs and found several errors:
```
Dec 24 13:12:21 Mantis PluginLoader[1459]: /home/deck/homebrew/plugins/decky-XRGaming/main.py:147: RuntimeWarning: coroutine 'Plugin.write_control_flags' was never awaited
Dec 24 13:12:21 Mantis PluginLoader[1459]:   self.write_control_flags({
Dec 24 13:12:21 Mantis PluginLoader[1459]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Dec 24 13:12:21 Mantis su[1463]: (to deck) root on none
Dec 24 13:12:21 Mantis PluginLoader[1451]: Migrating
Dec 24 13:12:21 Mantis PluginLoader[1451]: Initializing...
```

Can you try to remove `decky-XRGaming` folder from `/home/deck/homebrew/plugins/`?

In `cef_log.txt` I saw `142` errors related to `Minified react error`, last ones are related to `HLTB for Deck`,  `DeckSettings` & `DeckRoulette`:
```
[10944:10944:1224/131458.049195:INFO:CONSOLE(1)] "%c Decky %c PluginLoader %c background: #16a085; color: black; background: #FF0000; background: transparent; Error loading plugin HLTB for Deck TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[10944:10944:1224/131458.197905:INFO:CONSOLE(1)] "%c Decky %c PluginLoader %c background: #16a085; color: black; background: #FF0000; background: transparent; Error loading plugin DeckSettings TypeError: Cannot convert a Symbol value to a string", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[8909:8909:1224/131432.862348:INFO:CONSOLE(1)] "%c Decky %c PluginLoader %c background: #16a085; color: black; background: #FF0000; background: transparent; Error loading plugin DeckRoulette TypeError: Cannot convert a Symbol value to a string", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
```

<img width="2031" height="1013" alt="Image" src="https://github.com/user-attachments/assets/fd4a29c1-66f3-451f-99ee-d2eede9db679" />


>  I don't want to delete all my plugins though, is there any way to disable them and add them back one by one and keep their configs?

Can you try at least remove those plugins above and see if you will have any positive effect?

P.S:
There is a PR which add possibility to disable plugins from `Decky` settings: https://github.com/SteamDeckHomebrew/decky-loader/pull/850
But it needs more tests review. If someone can help with it, it will be nice!

**Comment by lowdown1983** [comment]
Reinstalled Cheat Deck and recreated my errors to get the screenshot.  
Working on the logs


![Image](https://github.com/user-attachments/assets/5ac7b7b9-6caa-4322-aba1-4ff68223a43c)
![Image](https://github.com/user-attachments/assets/b1a85c68-cd6c-4aa2-8ce5-d12cb5b51b94)
![Image](https://github.com/user-attachments/assets/6bd68271-3e69-442b-9ad6-5a529a3b8c4a)
![Image](https://github.com/user-attachments/assets/6877bd06-0b93-446b-a29e-23984aff0bdf)
![Image](https://github.com/user-attachments/assets/7f75ba29-045c-4960-adcb-7248708bdd6e)
![Image](https://github.com/user-attachments/assets/1e02b9a0-a5c6-4ebc-9792-ccf1e4df9922)
![Image](https://github.com/user-attachments/assets/cd8b0804-e3ae-4e1f-9e64-7259610b4c0b)

**Comment by ynhhoJ** [comment]
@lowdown1983, this error is caused by `CheatDeck`.
Did you tried to contact plugin developer?
I know that multiple users reported issues regarding this plugin, but I don't have any information if the plugin has an update or not.

P.S:
Usually within the first lines you can see the path of the file in which happened an error. When you see something like `plugins/CheatDeck`:
<img width="1537" height="93" alt="Image" src="https://github.com/user-attachments/assets/43d212e2-7437-430e-ac2a-21488e6d7163" />

You should report this to plugin developer...

**Comment by alcroito** [comment]
I'm having a similar issue since updating to 3.7.17. I can't even take a photo of the crash message or press any of the buttons, because the deck almost immediately tries to restart the steam app.

I was able to get the logs via ssh though.

[cef_log.txt](https://github.com/user-attachments/files/24359547/cef_log.txt)

[cef_log.previous.txt](https://github.com/user-attachments/files/24359548/cef_log.previous.txt)

[plugin_loader.log](https://github.com/user-attachments/files/24359549/plugin_loader.log)

CEF shows errors like:
```
[25024:25024:1228/123216.513512:INFO:CONSOLE(1)] "%c Decky %c PluginLoader %c background: #16a085; color: black; background: #FF0000; background: transparent; Error loading plugin HLTB for Deck TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[25024:25024:1228/123216.590207:INFO:CONSOLE(1)] "%c Decky %c PluginLoader %c background: #16a085; color: black; background: #FF0000; background: transparent; Error loading plugin Deck Settings TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[25024:25024:1228/123216.634934:INFO:CONSOLE(1)] "%c Decky %c PluginLoader %c background: #16a085; color: black; background: #FF0000; background: transparent; Error loading plugin Web Browser TypeError: Cannot convert a Symbol value to a string", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[25024:25024:1228/123216.736049:INFO:CONSOLE(1)] "%c Decky %c PluginLoader %c background: #16a085; color: black; background: #FF0000; background: transparent; Error loading plugin DeckSettings TypeError: Cannot convert a Symbol value to a string", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[25024:25024:1228/123216.763643:INFO:CONSOLE(1)] "Error: Minified React error #31; visit https://react.dev/errors/31?args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[25024:25024:1228/123216.890944:INFO:CONSOLE(1)] "Error: Minified React error #31; visit https://react.dev/errors/31?args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[25024:25024:1228/123216.911925:INFO:CONSOLE(1)] "Error: Minified React error #31; visit https://react.dev/errors/31?args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)
[25024:25024:1228/123216.950444:INFO:CONSOLE(2)] "Uncaught (in promise) Error: WHEN_CANCELLED", source: https://steamloopback.host/libraries/libraries~00299a408.js (2)
[25024:25024:1228/123217.100270:INFO:CONSOLE(2)] "Uncaught Error: Minified React error #31; visit https://react.dev/errors/31?args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.", source: https://steamloopback.host/libraries/libraries~00299a408.js (2)
[25024:25024:1228/123217.109110:INFO:CONSOLE(2)] "Uncaught Error: Minified React error #31; visit https://react.dev/errors/31?args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.", source: https://steamloopback.host/libraries/libraries~00299a408.js (2)
[25024:25024:1228/123217.361996:INFO:CONSOLE(1)] "GetFriendsList returned 2", source: https://steamloopback.host/chunk~2dcc5aaf7.js?contenthash=536b8bff02142a5fcd9a (1)

```

What hosts the files / chunks at `https://steamloopback.host`? Could it be some corrupted cached data?

**Comment by ynhhoJ** [comment]
> What hosts the files / chunks at https://steamloopback.host?

In `https://steamloopback.host/chunk...` is JavaScript code and some resources which Steam uses to display STEAM UI.

 > Could it be some corrupted cached data?
I don't think so...

Did you tried to remove those plugins and re-install them one by one from Stable / Testing store?
You should be able to remove those plugins folders from `ssh` 🤔

**Comment by alcroito** [comment]
Removing HLTB, Deck Settings, DeckSettings, and WebBrowser, and then reinstalling only 3 of them helped.
Unclear what was going wrong. 
The one I didn't install (DeckSettings, url https://github.com/davocarli/sharedeck-y ) has code that is 1-3 years old on github, perhaps some incompatibility with it.

**Comment by ynhhoJ** [comment]
>  Unclear what was going wrong.

Maybe you just had outdated plugins, which need to be updated to a version which supports the latest Steam OS update

**Comment by ROODAY** [comment]
So I ended up wiping decky, since I had the list of plugins here anyway. I manually deleted the plugins folder and then used the install script to wipe decky and reinstall, and then I added my plugins back manually, and it seems to be working fine? I did a hard shutdown (holding power button for 10 seconds) and rebooted and it started up fine, so perhaps it was some plugin that was out of date? Or perhaps for the css loader plugin maybe I had some themes that were out of date.

**Comment by ynhhoJ** [comment]
> so perhaps it was some plugin that was out of date?

I think yes

**Comment by ROODAY** [comment]
In that case would it make sense for the decky install/upgrade script to also check for any plugin updates and apply them as well? Otherwise we may get into a state where SteamOS and decky is updated, but the plugins are out of date and unable to be updated via decky UI.

**Comment by ynhhoJ** [comment]
@ROODAY, there is a PR which allows users to disable plugin which caused error: https://github.com/SteamDeckHomebrew/decky-loader/pull/841

After that, I think that user will be able to access `Decky` from `QAM` and check if he can update some plugins...

But idea with an `.sh` script is actually good 🤔 
I'll try to take a look

**Comment by danielandross** [comment]
I have the same issue for a while now. Would bei great to have that plug in update automated

**Comment by Kirit29** [comment]
> Reinstalled Cheat Deck and recreated my errors to get the screenshot. Working on the logs
> 
> ![Image](https://github.com/user-attachments/assets/5ac7b7b9-6caa-4322-aba1-4ff68223a43c) ![Image](https://github.com/user-attachments/assets/b1a85c68-cd6c-4aa2-8ce5-d12cb5b51b94) ![Image](https://github.com/user-attachments/assets/6bd68271-3e69-442b-9ad6-5a529a3b8c4a) ![Image](https://github.com/user-attachments/assets/6877bd06-0b93-446b-a29e-23984aff0bdf) ![Image](https://github.com/user-attachments/assets/7f75ba29-045c-4960-adcb-7248708bdd6e) ![Image](https://github.com/user-attachments/assets/1e02b9a0-a5c6-4ebc-9792-ccf1e4df9922) ![Image](https://github.com/user-attachments/assets/cd8b0804-e3ae-4e1f-9e64-7259610b4c0b)

Just FYI the cheatdeck version on decky store is Ancient. You would probably want to manually install the zip from it's github page

**Comment by DD1TTY** [comment]
I had this same issue. I started by using sudo rm -rf [decky_plugin_name] in /home/deck/homebrew/plugins/ a few at a time but ultimately ended up removing everything, running the decky uninstaller (choosing the option to _not_ keep the config), restarted and the steam deck booted up normally, then I reinstalled decky loader and just about all the same plugins and it is working perfectly again.

**Comment by craigvanaman** [comment]
I had this same issue. I think it was because I had an old version of Decky installed first. Fixed by:
1. completely uninstalling (inc. config) with the decky installer
2. reinstall with decky installer
3. restart steam deck

**Comment by PauloDaniel1993** [comment]
I have a clean install of decky in a reseted steam deck, but the issue persists

EDIT:
It works ok in bazzite though

EDIT2:
I formated my steam deck and my Legion Go S and it is not working. It works in rog ally xbox x with bazzite though

**Comment by AAGaming00** [comment]
outdated
